var t = {"searchRetrieveResponse":{"version":1.1, "numberOfRecords":38976, "resultSetId":"vnrbox", "resultSetIdleTime":300, "nextRecordPosition":1, "echoedSearchRetrieveRequest":{"version":1.1, "query":"iisg.collectionName exact \"hisco\"", "xQuery":{"searchClause":{"index":"iisg.collectionName", "relation":{"value":"exact"}, "term":"hisco"}}, "startRecord":1, "maximumRecords":10, "recordPacking":"string", "recordSchema":"info:srw\/schema\/1\/hisco"}, "diagnostics":{"diagnostic":{"uri":"info:srw\/diagnostic\/1\/66", "details":"info:srw\/schema\/1\/hisco"}},
    "extraResponseData":{"extraData":{"facetedResults":{"dataSource":{"facets":{"facet":[
        {"displayLabel":"hisco.country_code_label", "index":"hisco.country_code_label", "relation":"=", "terms":{"term":[
            {"actualTerm":"Portugal", "query":"hisco.country_code_label=Portugal", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Portugal&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1887},
            {"actualTerm":"France", "query":"hisco.country_code_label=France", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=France&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":10570},
            {"actualTerm":"Greece", "query":"hisco.country_code_label=Greece", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Greece&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":170},
            {"actualTerm":"Spain", "query":"hisco.country_code_label=Spain", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Spain&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1508},
            {"actualTerm":"Belgium", "query":"hisco.country_code_label=Belgium", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Belgium&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1575},
            {"actualTerm":"Canada (Quebec)", "query":"hisco.country_code_label=Canada (Quebec)", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Canada (Quebec)&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1293},
            {"actualTerm":"Denmark", "query":"hisco.country_code_label=Denmark", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Denmark&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1018},
            {"actualTerm":"Norway", "query":"hisco.country_code_label=Norway", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Norway&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1333},
            {"actualTerm":"Netherlands", "query":"hisco.country_code_label=Netherlands", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Netherlands&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":2302},
            {"actualTerm":"Germany", "query":"hisco.country_code_label=Germany", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Germany&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1306},
            {"actualTerm":"Great Britain", "query":"hisco.country_code_label=Great Britain", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Great Britain&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":2299},
            {"actualTerm":"Sweden", "query":"hisco.country_code_label=Sweden", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.country_code_label=Sweden&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":11664}
        ]}},
        {"displayLabel":"hisco.language_code_label", "index":"hisco.language_code_label", "relation":"=", "terms":{"term":[
            {"actualTerm":"Portugese", "query":"hisco.language_code_label=Portugese", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=Portugese&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1887},
            {"actualTerm":"Spanish", "query":"hisco.language_code_label=Spanish", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=Spanish&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":808},
            {"actualTerm":"Danish", "query":"hisco.language_code_label=Danish", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=Danish&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1017},
            {"actualTerm":"Greek", "query":"hisco.language_code_label=Greek", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=Greek&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":170},
            {"actualTerm":"Catalan", "query":"hisco.language_code_label=Catalan", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=Catalan&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":700},
            {"actualTerm":"French", "query":"hisco.language_code_label=French", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=French&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":13438},
            {"actualTerm":"German", "query":"hisco.language_code_label=German", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=German&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1306},
            {"actualTerm":"Swedish", "query":"hisco.language_code_label=Swedish", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=Swedish&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":11664},
            {"actualTerm":"Norwegian", "query":"hisco.language_code_label=Norwegian", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=Norwegian&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1333},
            {"actualTerm":"English", "query":"hisco.language_code_label=English", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=English&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":2299},
            {"actualTerm":"Dutch", "query":"hisco.language_code_label=Dutch", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.language_code_label=Dutch&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":2302}
        ]}},
        {"displayLabel":"hisco.product_label", "index":"hisco.product_label", "relation":"=", "terms":{"term":[
            {"actualTerm":"Ores and Minerals; Electricity, Gas and Water", "query":"hisco.product_label=Ores and Minerals; Electricity, Gas and Water", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.product_label=Ores and Minerals; Electricity, Gas and Water&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":100},
            {"actualTerm":"Other transportable goods - except Metal products, Machinery and Equipment", "query":"hisco.product_label=Other transportable goods - except Metal products, Machinery and Equipment", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.product_label=Other transportable goods - except Metal products, Machinery and Equipment&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":13},
            {"actualTerm":"Metal products, Machinery and Equipment", "query":"hisco.product_label=Metal products, Machinery and Equipment", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.product_label=Metal products, Machinery and Equipment&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":28},
            {"actualTerm":"Agriculture, Forestry and Fishery products", "query":"hisco.product_label=Agriculture, Forestry and Fishery products", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.product_label=Agriculture, Forestry and Fishery products&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":35907},
            {"actualTerm":"Food productsl Beverages and Tobacco; Textiles; Apparel and Leather products", "query":"hisco.product_label=Food productsl Beverages and Tobacco; Textiles; Apparel and Leather products", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.product_label=Food productsl Beverages and Tobacco; Textiles; Apparel and Leather products&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":46}
        ]}},
        {"displayLabel":"hisco.provenance_label", "index":"hisco.provenance_label", "relation":"=", "terms":{"term":[
            {"actualTerm":"Historical Sample of the Netherlands 1: 1850-1940", "query":"hisco.provenance_label=Historical Sample of the Netherlands 1: 1850-1940", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Historical Sample of the Netherlands 1: 1850-1940&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1171},
            {"actualTerm":"BALSAC database 1842-1971", "query":"hisco.provenance_label=BALSAC database 1842-1971", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=BALSAC database 1842-1971&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1293},
            {"actualTerm":"Spanish and Catalonian titles in Catalonian sources", "query":"hisco.provenance_label=Spanish and Catalonian titles in Catalonian sources", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Spanish and Catalonian titles in Catalonian sources&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1508},
            {"actualTerm":"PACO 16th-19th C", "query":"hisco.provenance_label=PACO 16th-19th C", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=PACO 16th-19th C&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1887},
            {"actualTerm":"Demographic Data Base 1803-1900", "query":"hisco.provenance_label=Demographic Data Base 1803-1900", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Demographic Data Base 1803-1900&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1365},
            {"actualTerm":"Knodel Village Genealogy Sample 1692-1950", "query":"hisco.provenance_label=Knodel Village Genealogy Sample 1692-1950", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Knodel Village Genealogy Sample 1692-1950&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1306},
            {"actualTerm":"History Data Service 1851", "query":"hisco.provenance_label=History Data Service 1851", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=History Data Service 1851&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1108},
            {"actualTerm":"Danish Data Archive census 1800", "query":"hisco.provenance_label=Danish Data Archive census 1800", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Danish Data Archive census 1800&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1018},
            {"actualTerm":"Norwegian Historical Data Centre 1900", "query":"hisco.provenance_label=Norwegian Historical Data Centre 1900", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Norwegian Historical Data Centre 1900&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1333},
            {"actualTerm":"Leverhulme Literacy Sample 1839-1914 1839-1914", "query":"hisco.provenance_label=Leverhulme Literacy Sample 1839-1914 1839-1914", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Leverhulme Literacy Sample 1839-1914 1839-1914&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1191},
            {"actualTerm":"Mykonos marriage acts 1859-1959", "query":"hisco.provenance_label=Mykonos marriage acts 1859-1959", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Mykonos marriage acts 1859-1959&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":170},
            {"actualTerm":"Historical Sample of the Netherlands 2: 1850-1940", "query":"hisco.provenance_label=Historical Sample of the Netherlands 2: 1850-1940", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Historical Sample of the Netherlands 2: 1850-1940&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1131},
            {"actualTerm":"Leuven nuptiality project 1800-1913", "query":"hisco.provenance_label=Leuven nuptiality project 1800-1913", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=Leuven nuptiality project 1800-1913&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1575},
            {"actualTerm":"TRA survey 1803-1945", "query":"hisco.provenance_label=TRA survey 1803-1945", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.provenance_label=TRA survey 1803-1945&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":2304}
        ]}},
        {"displayLabel":"hisco.status_label", "index":"hisco.status_label", "relation":"=", "terms":{"term":[
            {"actualTerm":"Principal", "query":"hisco.status_label=Principal", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Principal&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":350},
            {"actualTerm":"Subordinate", "query":"hisco.status_label=Subordinate", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Subordinate&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":874},
            {"actualTerm":"Owner, proprietor", "query":"hisco.status_label=Owner, proprietor", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Owner, proprietor&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":2987},
            {"actualTerm":"Serfs and Slaves", "query":"hisco.status_label=Serfs and Slaves", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Serfs and Slaves&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":5},
            {"actualTerm":"Graduate", "query":"hisco.status_label=Graduate", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Graduate&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":43},
            {"actualTerm":"Journeyman", "query":"hisco.status_label=Journeyman", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Journeyman&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":307},
            {"actualTerm":"'Worker'", "query":"hisco.status_label='Worker'", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label='Worker'&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":667},
            {"actualTerm":"Artisan", "query":"hisco.status_label=Artisan", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Artisan&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":58},
            {"actualTerm":"Student", "query":"hisco.status_label=Student", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Student&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":173},
            {"actualTerm":"Apprentice, learner", "query":"hisco.status_label=Apprentice, learner", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Apprentice, learner&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":271},
            {"actualTerm":"Nobility", "query":"hisco.status_label=Nobility", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Nobility&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":33},
            {"actualTerm":"Master", "query":"hisco.status_label=Master", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Master&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1581},
            {"actualTerm":"Lease-holder, share-cropper", "query":"hisco.status_label=Lease-holder, share-cropper", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Lease-holder, share-cropper&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":86},
            {"actualTerm":"Poor", "query":"hisco.status_label=Poor", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Poor&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":308},
            {"actualTerm":"Prestige titles", "query":"hisco.status_label=Prestige titles", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.status_label=Prestige titles&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":21}
        ]}},
        {"displayLabel":"hisco.relation_label", "index":"hisco.relation_label", "relation":"=", "terms":{"term":[
            {"actualTerm":"Future", "query":"hisco.relation_label=Future", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Future&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":103},
            {"actualTerm":"Former or retired", "query":"hisco.relation_label=Former or retired", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Former or retired&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":1053},
            {"actualTerm":"Wife or widow", "query":"hisco.relation_label=Wife or widow", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Wife or widow&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":26},
            {"actualTerm":"Other male relative", "query":"hisco.relation_label=Other male relative", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Other male relative&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":17},
            {"actualTerm":"Homeworker", "query":"hisco.relation_label=Homeworker", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Homeworker&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":229},
            {"actualTerm":"Voluntary, honorary", "query":"hisco.relation_label=Voluntary, honorary", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Voluntary, honorary&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":271},
            {"actualTerm":"Daughter", "query":"hisco.relation_label=Daughter", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Daughter&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":8},
            {"actualTerm":"Son", "query":"hisco.relation_label=Son", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Son&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":41},
            {"actualTerm":"Physical or mental disability", "query":"hisco.relation_label=Physical or mental disability", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Physical or mental disability&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":152},
            {"actualTerm":"Other female relative", "query":"hisco.relation_label=Other female relative", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.relation_label=Other female relative&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":18}
        ]}},
        {"displayLabel":"hisco.images", "index":"hisco.images", "relation":"=", "terms":{"term":[
            {"actualTerm":"Yes", "query":"hisco.images=Yes", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.images=Yes&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":20206},
            {"actualTerm":"No", "query":"hisco.images=No", "requestUrl":"http:\/\/api.iisg.nl\/solr\/hisco\/srw?query=iisg.collectionName exact \"hisco\" and hisco.images=No&recordSchema=info:srw\/schema\/1\/hisco&version=1.1&startRecord=1&operation=searchRetrieve", "count":18770}
        ]}}
    ]}}}, "databaseTitle":"Database Historical Occupations"}}}}